### ISSUE TITLE
Human-readable URLs

### ISSUE THREAD

**Issue by jtbandes** [hdoc/hdoc#17] opened 2022-07-22 18:50 UTC
Feature request: It would be nice to have the option to use human-readable URLs.

e.g. instead of https://mcap.dev/docs/cpp/r334C087DCDA491C1.html

the URL should look more like https://mcap.dev/docs/cpp/class-mcap::McapReader.html

For examples of how some other tools format their URLs, see:

https://mcap.dev/docs/python/apidoc/mcap.mcap0.reader.html
https://mcap.dev/docs/typescript/classes/Mcap0IndexedReader.html
https://mcap.dev/docs/swift/documentation/mcap/mcapstreamedreader

**Comment by hdoc** [comment] 2022-07-23 00:36
The current system of SymbolIDs which take the form of hashes (devoid of syntactic meaning) has many advantages, including: 

- Small storage space (just a u64)
- Ease of linking to other symbols in the HTML (the linker just needs to know the ID, not the full name of the symbol it's trying to link to)
- The ability to dump all of the HTML files into the same directory without any conflicts caused by symbols having the same name

This design decision was taken early on in the development of hdoc, long before it was open source. It has worked well, though it has ergonomic difficulties as you note. Changing the system to use human-readable URLs would require a significant refactoring of the HTML serializer, with the chief benefit that humans can now read the URLs. From our point of view, this is a meager benefit. The main readers of these URLs are search engines, who don't really care what the URL looks like. 

Few people, if any, are going to open a documentation page by entering the exact human-readable URL of the page they're looking for. Most of them will find it via search engine results, or by using hdoc's built in search, or by browsing the documentation pages. The URL is background information in each of these usecases, and as a result we don't see a need to make such sweeping changes  for such a meager benefit.

Closing this issue for now, but as always we would be happy to reconsider this in the future if the case for it becomes stronger.

**Closed as completed by hdoc** 2022-07-23 00:36 UTC
