### ISSUE TITLE
Hide Private Members?

### ISSUE THREAD

**Issue by jm4games** [hdoc/hdoc#5] opened 2021-10-29 02:47 UTC
Is there a way we could prevent including private members with documentation? They kind of clutter the docs generated with members that developers can't even use.

**Comment by hdoc** [comment] 2021-10-29 03:07
Currently there is no way to hide private members in the generated docs. This is something we've considered adding but we also want to keep configuration options and complexity to a minimum. 

Perhaps we could add a new option that shows private members by default and has the option to hide them. Something like `show_private_members = false` in .hdoc.toml. How does this sound?

**Comment by jm4games** [comment] 2021-10-29 03:57
That would actually be fine.

**Comment by hdoc** [comment] 2021-11-02 04:56
We will look to add this in the next release, but we can't promise anything yet. If you work at a company that needs this feature, please reach out to us at contact@hdoc.io and we can prioritize this. Thank you.

**Comment by jtbandes** [comment] 2022-03-25 01:06
In case anyone else ends up here looking for a solution — I found it was pretty simple to do a basic implementation of "hide private members", just two places need to be modified:

https://github.com/foxglove/mcap/blob/626bb50f2a094d3eea0829dfb5308816304e6903/cpp/hdoc.patch#L66-L84

This doesn't exclude private members from the search index, which would probably be a more correct solution, but this quick hack worked out alright!

**Comment by hdoc** [comment] 2022-03-25 06:14
Looks like it's time to upstream a solution to this issue, given that people are out there patching hdoc to solve it. Look for this in the next release.

**Comment by hdoc** [comment] 2022-05-26 04:24
@jm4games @jtbandes there's now a fix for this in the mainline with the latest version 1.2.3. Check out the [release notes](https://hdoc.io/release-notes/#version-1-2-3-25-may-2022) for more details. I have also credited both of you in the release notes. Thank you!

**Comment by jm4games** [comment] 2022-05-26 15:34
Thanks a lot, much appreciated!!

**Comment by jtbandes** [comment] 2022-06-06 23:26
Thanks for the update. I just tried this out, but it is failing with:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
```
 https://github.com/foxglove/mcap/runs/6764834723?check_suite_focus=true

You can reproduce the error by running `cd cpp && make ci-docs` on this branch: https://github.com/foxglove/mcap/pull/408

**Comment by hdoc** [comment] 2022-06-07 00:04
Thank you for reporting the issue and providing repro docs. Looks like something slipped by our internal CI. We’ll take a look and get a fix out ASAP.

**Comment by hdoc** [comment] 2022-06-07 03:38
@jtbandes this issue should be fixed in version 1.2.4, which was just released. It was a logic bug, and there are now unit tests to cover this functionality. You are credited in the [release notes](https://hdoc.io/release-notes/#version-1-2-4-6-june-2022). Thank you for your help!

**Closed as completed by hdoc** 2022-06-07 03:38 UTC

**Comment by jtbandes** [comment] 2022-06-07 18:02
Thanks, that's working now!

**Comment by ekmecic** [comment] 2022-06-07 18:05
Happy to hear it!
